--- 
- name: Installing multiple packages using loops
  hosts: all
  become: true

  # vars: 
  #   package_name:
  #     Ubuntu: apache2
  #     Amazon: httpd

  tasks:

    - name: Installing packages on Ubuntu
      apt: 
        name: "{{item}}"
        state: present
      with_items:
        - nginx
        - apache2
        - git 
        - nodejs
      when: ansible_distribution == "Ubuntu"

    - name: Installing packages on Amazon Al2
      yum: 
        name: "{{item}}"
        state: present
      with_items:
        - nginx
        - httpd
        - git 
        - nodejs
      when: ansible_distribution == "Amazon"