---
    - name: Install apache on dynamically added Ec2 instance
      become: yes 
      package: 
        name: httpd
        state: present
      # delegate_to: "{{ item }}"
      with_items: "{{groups['dynamic_hosts']}}"
      vars: 
        ansible_ssh_private_key_file: "/home/aarish/Desktop/Devops/ansible2.pem"
        ansible_user: ec2-user
      when: groups['dynamic_hosts'] is defined and groups['dynamic_hosts'] | length > 0

    - name: start apache
      become: yes
      service:
        name: httpd
        state: started
        enabled: yes
# tasks file for webserver_config
